name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.0.1
      with:
        cache-on-failure: "false"

    - name: Check for compile errors
      run: cargo check
